name: CI&CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t mew_server:0.0.1 .

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Shut down services
        if: always()
        run: |
          docker-compose down
